#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

for cmd in python3 bash; do
  command -v "$cmd" >/dev/null || { echo "[fail] missing dependency: $cmd" >&2; exit 1; }
done

python3 -m py_compile app/*.py scripts/*.py tests/*.py
for script in scripts/*.sh; do
  bash -n "$script"
done
python3 tests/test_controller.py
python3 tests/test_scenarios.py

python3 - <<'PY'
from pathlib import Path

required = {
    "Dockerfile",
    "README.md",
    "kind-config.yaml",
    "app/agent.py",
    "app/controller.py",
    "docs/architecture.svg",
    "k8s/namespace.yaml",
    "k8s/parameters.yaml",
    "k8s/master.yaml",
    "k8s/agents.yaml",
    "scripts/run_demo.sh",
    "scripts/verify_demo.sh",
    "scripts/wait_for_completion.sh",
    "scripts/collect_results.sh",
    "scripts/validate_results.py",
    "scripts/history_to_csv.py",
    "scripts/delete_cluster.sh",
    "tests/test_controller.py",
    "tests/test_scenarios.py",
}
missing = sorted(path for path in required if not Path(path).is_file())
assert not missing, f"missing package files: {missing}"

text = "\n".join(
    path.read_text(encoding="utf-8", errors="ignore")
    for path in Path(".").rglob("*")
    if path.is_file() and ".git" not in path.parts and path.as_posix() != "scripts/self_check.sh"
)
for forbidden in ("ChatGPT", "OpenAI", "generated by AI", "AI-generated"):
    assert forbidden.lower() not in text.lower(), f"forbidden marker found: {forbidden}"

parameters = Path("k8s/parameters.yaml").read_text(encoding="utf-8")
for item in (
    'RESIDUAL_THRESHOLD: "1400"',
    'PREDICTION_HORIZON: "5"',
    'GC_INTERVAL: "15"',
    'GC_RECLAIM_RATIO: "75"',
    'MAX_CYCLES: "240"',
    'CYCLE_DURATION: "0.05"',
):
    assert item in parameters, f"missing expected parameter: {item}"

kind_config = Path("kind-config.yaml").read_text(encoding="utf-8")
assert kind_config.count("role: worker") == 3, "KinD config must define three workers"
assert kind_config.count("role: control-plane") == 1, "KinD config must define one control-plane"

for manifest in ("k8s/master.yaml", "k8s/agents.yaml"):
    manifest_text = Path(manifest).read_text(encoding="utf-8")
    assert "__SCENARIO__" in manifest_text, f"missing scenario placeholder in {manifest}"
    assert "__RUN_ID__" in manifest_text, f"missing run_id placeholder in {manifest}"
    assert "residual-multinode-demo:1.2" in manifest_text, f"image tag mismatch in {manifest}"

run_script = Path("scripts/run_demo.sh").read_text(encoding="utf-8")
assert "delete daemonset gc-agent-upf" in run_script, "agents must be removed between scenarios"
assert "delete deployment gc-master" in run_script, "master must be reset between scenarios"
assert 'run_scenario "UPF-noGC"' in run_script and 'run_scenario "UPF-withGC"' in run_script

# Keep the shell scripts portable across the default macOS and Linux toolsets.
for script_name in ("scripts/wait_for_completion.sh", "scripts/collect_results.sh"):
    script_text = Path(script_name).read_text(encoding="utf-8")
    nonportable_loop = "$(" + "s" + "eq "
    assert nonportable_loop not in script_text, f"non-portable numeric loop in {script_name}"
    assert "for ((attempt = 1; attempt <= 40; attempt++))" in script_text, (
        f"portable readiness loop missing in {script_name}"
    )

print("PASS package structure and static content")
PY

echo "[ok] local checks passed"
